[profile.default]
src = "src"
out = "out"
libs = ["lib"]

ffi = true
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
    "@poseidon/=lib/poseidon2-evm/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@solarity/=lib/solidity-lib/"
]